-- Seed module_status and test_progress
INSERT INTO public.module_status (module_id, status)
VALUES
  ('website_settings', 'pending'),
  ('website_payment_filter_by_product', 'pending'),
  ('website_sale_custom', 'pending'),
  ('theme_macstation', 'pending'),
  ('payment_mercadopago', 'pending'),
  ('payment_mercadopago_discounts', 'pending'),
  ('payment_modo', 'pending'),
  ('extended_warranty_macstation', 'pending'),
  ('product_tag_enhancement', 'pending'),
  ('product_compatibility', 'pending'),
  ('stock_product_tag_compat', 'pending'),
  ('stock_valuation_product_tag', 'pending'),
  ('account_product_tag', 'pending'),
  ('sale_report_product_tag', 'pending'),
  ('payment_talo', 'pending'),
  ('website_product_zones', 'pending'),
  ('fb_xml_feed', 'pending'),
  ('custom_product_attributes', 'pending'),
  ('hide_ecommerce_categories', 'pending'),
  ('product_variant_images', 'pending'),
  ('website_product_ribbons', 'pending'),
  ('website_sale_product_search', 'pending'),
  ('website_sale_seo', 'pending'),
  ('fb_pixel', 'pending'),
  ('ga4_pixel', 'pending'),
  ('gtm_pixel', 'pending'),
  ('eb_website_sale_google_analytics_4', 'pending')
ON CONFLICT (module_id) DO NOTHING;

INSERT INTO public.test_progress (module_id, step_id, done, result)
VALUES
  ('website_settings', 'ws-1', false, 'pending'),
  ('website_settings', 'ws-2', false, 'pending'),
  ('website_settings', 'ws-3', false, 'pending'),
  ('website_settings', 'ws-4', false, 'pending'),
  ('website_payment_filter_by_product', 'wpf-1', false, 'pending'),
  ('website_payment_filter_by_product', 'wpf-2', false, 'pending'),
  ('website_payment_filter_by_product', 'wpf-3', false, 'pending'),
  ('website_payment_filter_by_product', 'wpf-4', false, 'pending'),
  ('website_payment_filter_by_product', 'wpf-5', false, 'pending'),
  ('website_payment_filter_by_product', 'wpf-6', false, 'pending'),
  ('website_payment_filter_by_product', 'wpf-7', false, 'pending'),
  ('website_sale_custom', 'wsc-1', false, 'pending'),
  ('website_sale_custom', 'wsc-2', false, 'pending'),
  ('website_sale_custom', 'wsc-3', false, 'pending'),
  ('website_sale_custom', 'wsc-4', false, 'pending'),
  ('website_sale_custom', 'wsc-5', false, 'pending'),
  ('website_sale_custom', 'wsc-6', false, 'pending'),
  ('website_sale_custom', 'wsc-7', false, 'pending'),
  ('website_sale_custom', 'wsc-8', false, 'pending'),
  ('theme_macstation', 'tm-1', false, 'pending'),
  ('theme_macstation', 'tm-2', false, 'pending'),
  ('theme_macstation', 'tm-3', false, 'pending'),
  ('theme_macstation', 'tm-4', false, 'pending'),
  ('theme_macstation', 'tm-5', false, 'pending'),
  ('theme_macstation', 'tm-6', false, 'pending'),
  ('theme_macstation', 'tm-7', false, 'pending'),
  ('theme_macstation', 'tm-8', false, 'pending'),
  ('payment_mercadopago', 'mp-1', false, 'pending'),
  ('payment_mercadopago', 'mp-2', false, 'pending'),
  ('payment_mercadopago', 'mp-3', false, 'pending'),
  ('payment_mercadopago', 'mp-4', false, 'pending'),
  ('payment_mercadopago', 'mp-5', false, 'pending'),
  ('payment_mercadopago', 'mp-6', false, 'pending'),
  ('payment_mercadopago_discounts', 'mpd-1', false, 'pending'),
  ('payment_mercadopago_discounts', 'mpd-2', false, 'pending'),
  ('payment_mercadopago_discounts', 'mpd-3', false, 'pending'),
  ('payment_mercadopago_discounts', 'mpd-4', false, 'pending'),
  ('payment_mercadopago_discounts', 'mpd-5', false, 'pending'),
  ('payment_modo', 'modo-1', false, 'pending'),
  ('payment_modo', 'modo-2', false, 'pending'),
  ('payment_modo', 'modo-3', false, 'pending'),
  ('payment_modo', 'modo-4', false, 'pending'),
  ('payment_modo', 'modo-5', false, 'pending'),
  ('payment_modo', 'modo-6', false, 'pending'),
  ('extended_warranty_macstation', 'ewm-1', false, 'pending'),
  ('extended_warranty_macstation', 'ewm-2', false, 'pending'),
  ('extended_warranty_macstation', 'ewm-3', false, 'pending'),
  ('extended_warranty_macstation', 'ewm-4', false, 'pending'),
  ('extended_warranty_macstation', 'ewm-5', false, 'pending'),
  ('extended_warranty_macstation', 'ewm-6', false, 'pending'),
  ('extended_warranty_macstation', 'ewm-7', false, 'pending'),
  ('extended_warranty_macstation', 'ewm-8', false, 'pending'),
  ('extended_warranty_macstation', 'ewm-9', false, 'pending'),
  ('extended_warranty_macstation', 'ewm-10', false, 'pending'),
  ('product_tag_enhancement', 'pte-1', false, 'pending'),
  ('product_tag_enhancement', 'pte-2', false, 'pending'),
  ('product_tag_enhancement', 'pte-3', false, 'pending'),
  ('product_compatibility', 'pc-1', false, 'pending'),
  ('product_compatibility', 'pc-2', false, 'pending'),
  ('product_compatibility', 'pc-3', false, 'pending'),
  ('product_compatibility', 'pc-4', false, 'pending'),
  ('stock_product_tag_compat', 'sptc-1', false, 'pending'),
  ('stock_product_tag_compat', 'sptc-2', false, 'pending'),
  ('stock_product_tag_compat', 'sptc-3', false, 'pending'),
  ('stock_valuation_product_tag', 'svpt-1', false, 'pending'),
  ('stock_valuation_product_tag', 'svpt-2', false, 'pending'),
  ('account_product_tag', 'apt-1', false, 'pending'),
  ('account_product_tag', 'apt-2', false, 'pending'),
  ('account_product_tag', 'apt-3', false, 'pending'),
  ('sale_report_product_tag', 'srpt-1', false, 'pending'),
  ('sale_report_product_tag', 'srpt-2', false, 'pending'),
  ('sale_report_product_tag', 'srpt-3', false, 'pending'),
  ('payment_talo', 'talo-1', false, 'pending'),
  ('payment_talo', 'talo-2', false, 'pending'),
  ('payment_talo', 'talo-3', false, 'pending'),
  ('payment_talo', 'talo-4', false, 'pending'),
  ('website_product_zones', 'wpz-1', false, 'pending'),
  ('website_product_zones', 'wpz-2', false, 'pending'),
  ('website_product_zones', 'wpz-3', false, 'pending'),
  ('website_product_zones', 'wpz-4', false, 'pending'),
  ('fb_xml_feed', 'fbx-1', false, 'pending'),
  ('fb_xml_feed', 'fbx-2', false, 'pending'),
  ('fb_xml_feed', 'fbx-3', false, 'pending'),
  ('fb_xml_feed', 'fbx-4', false, 'pending'),
  ('custom_product_attributes', 'cpa-1', false, 'pending'),
  ('custom_product_attributes', 'cpa-2', false, 'pending'),
  ('custom_product_attributes', 'cpa-3', false, 'pending'),
  ('hide_ecommerce_categories', 'hec-1', false, 'pending'),
  ('hide_ecommerce_categories', 'hec-2', false, 'pending'),
  ('hide_ecommerce_categories', 'hec-3', false, 'pending'),
  ('product_variant_images', 'pvi-1', false, 'pending'),
  ('product_variant_images', 'pvi-2', false, 'pending'),
  ('product_variant_images', 'pvi-3', false, 'pending'),
  ('website_product_ribbons', 'wpr-1', false, 'pending'),
  ('website_product_ribbons', 'wpr-2', false, 'pending'),
  ('website_product_ribbons', 'wpr-3', false, 'pending'),
  ('website_product_ribbons', 'wpr-4', false, 'pending'),
  ('website_sale_product_search', 'wsps-1', false, 'pending'),
  ('website_sale_product_search', 'wsps-2', false, 'pending'),
  ('website_sale_product_search', 'wsps-3', false, 'pending'),
  ('website_sale_seo', 'wss-1', false, 'pending'),
  ('website_sale_seo', 'wss-2', false, 'pending'),
  ('website_sale_seo', 'wss-3', false, 'pending'),
  ('website_sale_seo', 'wss-4', false, 'pending'),
  ('website_sale_seo', 'wss-5', false, 'pending'),
  ('fb_pixel', 'fbp-1', false, 'pending'),
  ('fb_pixel', 'fbp-2', false, 'pending'),
  ('fb_pixel', 'fbp-3', false, 'pending'),
  ('ga4_pixel', 'ga4p-1', false, 'pending'),
  ('ga4_pixel', 'ga4p-2', false, 'pending'),
  ('ga4_pixel', 'ga4p-3', false, 'pending'),
  ('gtm_pixel', 'gtm-1', false, 'pending'),
  ('gtm_pixel', 'gtm-2', false, 'pending'),
  ('gtm_pixel', 'gtm-3', false, 'pending'),
  ('eb_website_sale_google_analytics_4', 'ebga-1', false, 'pending'),
  ('eb_website_sale_google_analytics_4', 'ebga-2', false, 'pending'),
  ('eb_website_sale_google_analytics_4', 'ebga-3', false, 'pending'),
  ('eb_website_sale_google_analytics_4', 'ebga-4', false, 'pending'),
  ('eb_website_sale_google_analytics_4', 'ebga-5', false, 'pending')
ON CONFLICT (module_id, step_id) DO NOTHING;
